# Generated by Django 4.2.2 on 2023-06-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_category_options_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='descriptin',
            new_name='description',
        ),
    ]
