# Generated by Django 4.2.2 on 2023-06-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_descriptin_ticket_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
    ]
