# Generated by Django 4.2.2 on 2023-06-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
