# Generated by Django 4.2.2 on 2023-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_registration_ticket_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Credit Card'), ('P', 'PayPal'), ('N', 'Not Required')], default='N', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('W', 'Waitlisted')], default='A', max_length=1),
        ),
    ]
