# Generated by Django 5.0 on 2023-12-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_registration_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
