# Generated by Django 5.0.1 on 2024-02-01 11:02

import events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_profile_image_alter_eventimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/images', validators=[events.validators.validate_image_size]),
        ),
    ]
