# Generated by Django 5.0.1 on 2024-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_reservation_code_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='qrcodes'),
        ),
    ]
