# Generated by Django 5.0.1 on 2024-02-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_ticket_needs_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='waitlist_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
