# Generated by Django 5.0.1 on 2024-02-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_ticket_waitlist_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
