databases:
  - name: evently
    plan: free
    databaseName: evently_idl4
    user: evently_idl4_user

services:
  - type: web
    plan: free
    name: evently
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn evently.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: evently
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4